### ISSUE TITLE
SDK Documentation

### ISSUE THREAD

**Issue by r0wdy1** [zkBob/zkbob-client-js#133]
We need a comprehensive document for developers who want to integrate ZKbob in different environments and user flows.
The document must describe basic operations such as 
- signup
- sync state
- generate receiving address
- check address
- deposit
- transfer
- withdraw
- get history
- compliance report
- export seed
- switch pool

**Comment by r0wdy1** [comment]
cc @maikReal

**Comment by EvgenKor** [comment]
https://docs.zkbob.com/implementation/client-library-sdk
