### ISSUE TITLE
Permit2 support

### ISSUE THREAD

**Issue by r0wdy1** [zkBob/zkbob-client-js#137]
Probably we need to have a similar to relayer map between tokens and type of permit support, so that when a user tries to deposit a token that doesn't support 2612, there will be an extra step where user must is first asked to make an approve call to permit contract and only then we get back to the standard workflow and ask her to create a signature
here's and updated scheme for using permit2 in deposits:
![image](https://github.com/zkBob/zkbob-client-js/assets/103738251/29b89e01-72c0-47b7-a346-e39b28783006)

The decision to make an extra call is made on the SDK side . It seems to be a convenient task to refactor communication between UI and SDK and to move signing logic to SDK with occasional status callback invocations:
![permit_states drawio (1)](https://github.com/zkBob/zkbob-client-js/assets/103738251/a8039922-30bc-44df-86fe-4fef18dc18cd)

Signature transfer object required by permit2:
https://github.com/Uniswap/permit2-sdk/blob/cb84da1accf9f475d11e96fff7e5b255d55dcc14/src/signatureTransfer.ts#L19
we could use https://www.npmjs.com/package/@uniswap/permit2-sdk

**Comment by EvgenKor** [comment]
PR #140

**Comment by maikReal** [comment]
Add the method to work with DD
