### ISSUE TITLE
Forced exit

### ISSUE THREAD

**Issue by k1rill-fedoseev** [zkBob/zkbob-client-js#139]
## What to do? 

Give a user to withdraw their funds if the relayer is down and unavailable

Detailed description + decomposition: https://www.notion.so/blockscout/Emergency-exit-727cc6e0aa934d67b18ec23165debeb4

**Comment by maikReal** [comment]
@r0wdy1 Add decomposition, please

**Comment by maikReal** [comment]
**UPD 17.11:** Add instructions: on how to deploy the console locally and make a forced exit using the console to GitBook (@EvgenKor). We'll use it for the forced exit announcement

**Comment by maikReal** [comment]
**UPD 27.11:**

1. We need only to deploy contracts on prod and that's all
2. With the dec relayer it doesn't make sense to use forced exit. Everyone could be a relayer for himself
3. Decided to continue discussing the current topic later, when the first version of dec relayer is finished
