### ISSUE TITLE
Support forced exits in the client SDK

### ISSUE THREAD

**Issue by k1rill-fedoseev** [zkBob/zkbob-client-js#162]
Contracts reference: https://github.com/zkBob/zkbob-contracts/blob/9b54085963c581a58ca6382566179928dadc9cb7/src/zkbob/ZkBobPool.sol#L342-L448
SDK should support 4 new actions:
1. Commit a forced exit for the current account nullifier, by calculating a withdrawal proof. Method should accept `to` and optional `operator` as arguments.
2. Check if a forced exit was committed for the current account nullifier. If it was, function should traverse contract logs backwards until the first matching `CommitForcedExit` event is found. Function should return a `CommitForcedExit`-like struct.
3. Execute a given forced exit for the current account nullifier. Method should accept `CommitForcedExit`-like struct, check if it matches onchain forced exit hash, exit deadlines are respected and optional operator matches the sender. Then it should send the execute transaction.
4. Cancel a given forced exit after deadline. Method should accept `CommitForcedExit`-like struct, check if it matches onchain forced exit hash, exit deadline has passed. Then it should send the cancellation transaction.

**Comment by EvgenKor** [comment]
Implemented in #166

**Comment by maikReal** [comment]
Duplicated task: https://github.com/zkBob/zkbob-client-js/issues/139
