### ISSUE TITLE
Library: Optimize parameter loading process (Keep transfer parameters in cache)

### ISSUE THREAD

**Issue by akolotov** [zkBob/zkbob-client-js#30]
Consider to keep [transfer parameters](https://github.com/zkBob/zkbob-contracts/tree/master/src/zkbob/verifiers/prodV1) in the browser cache and upload new version only if they were changed on the relayer/pool contract. This improvement will reduce amount of data downloaded by the app when it is opened by the user.

**Comment by EvgenKor** [comment]
Closed by PR #32
