### ISSUE TITLE
Library: Multi-sender

### ISSUE THREAD

**Issue by ulyanas** [zkBob/zkbob-client-js#37]
Make transfer to several different recipients in one transaction

**Comment by ulyanas** [comment]
@EvgenKor Could you please add instructions how to check? Via UI console?

**Comment by EvgenKor** [comment]
@ulyanas Yes the only way to check it - through console. But you can launch it with this feature with a local deploy only because library is unpublished yet (waiting for code review #42 and other ongoing changes)

**Comment by ulyanas** [comment]
@EvgenKor  Noted, thank you! 
CC @vadimnikonov1

**Comment by EvgenKor** [comment]
The current staging console with multitransfer support [has been deployed](https://console.thgkjlr.website/)
Please add a plus sign to the regular syntax of the `transfer-shielded` command to launch multisender mode
<img width="810" alt="image" src="https://user-images.githubusercontent.com/1415489/198547679-878782b7-acc1-4061-a218-0d22f60e5319.png">

**Comment by vadimnikonov1** [comment]
QA review - OK
