### ISSUE TITLE
Library: Track rejected transactions {R06.12}

### ISSUE THREAD

**Issue by ulyanas** [zkBob/zkbob-client-js#38]
The problem: a user submits a transaction which is finally rejected on the contract, it disappears silently from UI

**Comment by maikReal** [comment]
We need to make changes in relayer and lib that will help UI show rejected transactions

**Comment by ulyanas** [comment]
+ 
[ ] Add multi-transfer case

**Comment by ulyanas** [comment]
Need to check PR

**Comment by EvgenKor** [comment]
The current staging console with history tracking  support [has been deployed](https://console.thgkjlr.website/)
History now supports multisender transfers and failure tracking. History example (use `history` command in the console):

<img width="1370" alt="image" src="https://user-images.githubusercontent.com/1415489/198551392-661d156d-fb04-4488-abb8-ecf8bebca1fd.png">

**Comment by vadimnikonov1** [comment]
QA review console - OK

**Comment by vadimnikonov1** [comment]
Need changes to UX/UI
