### ISSUE TITLE
Library: state updating progress {R06.12}

### ISSUE THREAD

**Issue by EvgenKor** [zkBob/zkbob-client-js#43]
The client library should provide to the UI approximate state updating progress (processed_tx_cnt \ total_tx_cnt)
This progress will bring to the application through callback

**Comment by EvgenKor** [comment]
The feature will not be ready for the next release due to a lot of pending changes in associated code. Moreover the sync approach can be changed in the near time so there are no reasons to implement this feature right now

**Comment by r0wdy1** [comment]
Postponed because of another more urgent task #55

**Comment by EvgenKor** [comment]
#160
