### ISSUE TITLE
Mobile version (web)

### ISSUE THREAD

**Issue by AllFi** [zkBob/zkbob-client-js#47]
1. Need to test assumptions that simple consequential proof generation might work in iOS Safari

2. Test on Android, debug current issues on Android

**Comment by AllFi** [comment]
Waiting for PRs:
1. https://github.com/zkBob/libzkbob-rs/pull/32
2. https://github.com/zkBob/libzkbob-rs/pull/34
3. https://github.com/zkBob/zkbob-client-js/pull/65
4. https://github.com/zkBob/zkbob-console/pull/35

After that, it is necessary to make small change in `zkbob-ui`. See https://github.com/zkBob/zkbob-client-js/pull/65.

**Comment by vadimnikonov1** [comment]
IOS: Safari and Google Chrome are OK

**Comment by vadimnikonov1** [comment]
![Image](https://user-images.githubusercontent.com/84346846/210338729-d0761181-4b42-46b8-820f-21fcf78b0944.png)

**Comment by vadimnikonov1** [comment]
<div ccp_infra_version='3' ccp_infra_timestamp='1672759540283' ccp_infra_user_hash='3164484720' ccp_infra_copy_id='5848720e-5d6f-4f1f-8986-30367f180a55' data-ccp-timestamp='1672759540283'><html><head><meta name=ProgId content=Excel.Sheet><meta name=Generator content="Microsoft Excel 15"><style>table
	{mso-displayed-decimal-separator:"\,";
	mso-displayed-thousand-separator:" ";}
tr
	{mso-height-source:auto;}
col
	{mso-width-source:auto;}
td
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Calibri, sans-serif;
	mso-font-charset:0;
	text-align:general;
	vertical-align:bottom;
	border:none;
	white-space:nowrap;
	mso-rotate:0;}
.xl16
	{border-top:.5pt solid black;
	border-right:none;
	border-bottom:.5pt solid black;
	border-left:.5pt solid black;}
.xl17
	{color:black;
	font-family:Calibri;
	mso-generic-font-family:auto;
	mso-font-charset:1;
	border:.5pt solid black;}
.xl18
	{border-top:none;
	border-right:.5pt solid black;
	border-bottom:.5pt solid black;
	border-left:.5pt solid black;}
.xl20
	{text-align:center;
	border-top:none;
	border-right:none;
	border-bottom:.5pt solid black;
	border-left:.5pt solid black;}
.xl21
	{color:black;
	font-family:Calibri;
	mso-generic-font-family:auto;
	mso-font-charset:1;
	text-align:center;
	border-top:none;
	border-right:.5pt solid black;
	border-bottom:.5pt solid black;
	border-left:.5pt solid black;}
.xl22
	{border:.5pt solid black;
	white-space:normal;}
.xl23
	{border-top:.5pt solid black;
	border-right:.5pt solid black;
	border-bottom:none;
	border-left:.5pt solid black;
	white-space:normal;}
.xl24
	{border-top:none;
	border-right:.5pt solid black;
	border-bottom:.5pt solid black;
	border-left:.5pt solid black;
	white-space:normal;}
.xl29
	{text-align:center;
	border:.5pt solid black;
	background:#C6E0B4;
	mso-pattern:black none;
	white-space:normal;}
.xl30
	{text-align:center;
	border-top:.5pt solid black;
	border-right:.5pt solid black;
	border-bottom:none;
	border-left:.5pt solid black;
	background:#C6E0B4;
	mso-pattern:black none;
	white-space:normal;}
.xl31
	{text-align:center;
	border-top:none;
	border-right:.5pt solid black;
	border-bottom:.5pt solid black;
	border-left:.5pt solid black;
	background:#C65911;
	mso-pattern:black none;
	white-space:normal;}
.xl35
	{text-align:center;
	border-top:.5pt solid black;
	border-right:none;
	border-bottom:.5pt solid black;
	border-left:.5pt solid black;}
.xl37
	{text-align:center;
	border-top:.5pt solid black;
	border-right:none;
	border-bottom:.5pt solid black;
	border-left:.5pt solid black;
	background:#C6E0B4;
	mso-pattern:black none;
	white-space:normal;}
.xl38
	{text-align:center;
	border-top:.5pt solid black;
	border-right:none;
	border-bottom:none;
	border-left:.5pt solid black;
	background:#C6E0B4;
	mso-pattern:black none;
	white-space:normal;}
.xl39
	{text-align:center;
	border-top:none;
	border-right:none;
	border-bottom:.5pt solid black;
	border-left:.5pt solid black;
	background:#C65911;
	mso-pattern:black none;
	white-space:normal;}
.xl40
	{color:black;
	font-size:14.0pt;
	font-weight:700;
	font-family:Calibri;
	mso-generic-font-family:auto;
	mso-font-charset:0;
	text-align:center;
	border-top:.5pt solid black;
	border-right:none;
	border-bottom:.5pt solid black;
	border-left:.5pt solid black;}
.xl41
	{text-align:center;
	border-top:.5pt solid black;
	border-right:none;
	border-bottom:.5pt solid black;
	border-left:none;}
.xl42
	{color:black;
	font-size:14.0pt;
	font-weight:700;
	font-family:Calibri;
	mso-generic-font-family:auto;
	mso-font-charset:0;
	text-align:center;
	border-top:.5pt solid black;
	border-right:.5pt solid black;
	border-bottom:.5pt solid black;
	border-left:none;}
.xl91
	{text-align:center;
	border:.5pt solid black;
	background:#C65911;
	mso-pattern:black none;
	white-space:normal;}
.xl92
	{text-align:center;
	border-top:.5pt solid black;
	border-right:.5pt solid black;
	border-bottom:none;
	border-left:.5pt solid black;}
.xl93
	{text-align:center;
	border-top:none;
	border-right:.5pt solid black;
	border-bottom:.5pt solid black;
	border-left:.5pt solid black;
	background:#C6E0B4;
	mso-pattern:black none;
	white-space:normal;}
</style></head><body link="#0563C1" vlink="#954F72">

  | IOS | Android
-- | -- | --
  | Safari | Google Chrome | Google Chrome | FireFox
Create zkAccount with seed phrase | Yes | Yes | Yes | Yes
Create zkAccount with wallet | Yes | Yes | Yes | Yes
Restore account | Yes | Yes | Yes | Yes
Connect wallet(Metamask) | No | No | No | No
Connect wallet(WalletConnect) | Yes | Yes | Yes | Yes
Deposit | Yes(40s) | Yes | Yes | Yes
Transfer | Yes(40s) | Yes | Yes | Yes
Multitransfer | Yes(40s) | Yes | Yes | Yes
Withdraw | Yes(40s) for 1 transaction | Yes | Yes | Yes
Get BOB | Yes | Yes | Yes | Yes

</body></html></div>
