### ISSUE TITLE
Chrome for Android support

### ISSUE THREAD

**Issue by AllFi** [zkBob/zkbob-client-js#50]
It seems that there is a problem with shared wasm memory support in chrome (https://caniuse.com/mdn-javascript_builtins_webassembly_memory_memory_shared). That's why zkBob isn't working in Chrome for Android now. We could fix it if we move all interactions with wasm in Web Worker.

**Comment by AllFi** [comment]
Plan:
- [ ] Add ability to use IndexedDB in Web Worker in kvdb_web (libzkbob-rs)
- [ ] Move all interactions with wasm in Web Worker
- [ ] Confirm that zkBob works properly in Chrome for Android after these modifications
- [ ] Regression testing

**Comment by maikReal** [comment]
The library is ready, but we need help from @maxaleks

**Comment by AllFi** [comment]
It seems that there is no difference between Local Storage and IndexedDB on Desktop and Mobile. It is worth noting that Local Storage and IndexedDB have some security issues that deserve consideration but definitely not in the issue.

**Comment by AllFi** [comment]
There is an example of necessary UI changes at https://github.com/zkBob/zkbob-ui/pull/89.

**Comment by vadimnikonov1** [comment]
Device: Samsung Galaxy A30

Chrome for Android: Prod
Deposit OK (5m)
Transfer OK (4m)
Multitransfer OK (4m)
Withdrawal OK (5m)
Create zkAccount with Seed phrase OK
Connect zkAccount with MM OK
Restore zkAccount with Seed phrase OK

There is no way to test the functionality of the app on the Stage as it's not possible to connect an external wallet.
