### ISSUE TITLE
Getting address belonging to the account

### ISSUE THREAD

**Issue by EvgenKor** [zkBob/zkbob-client-js#54]
It's need to parse shielded address and get if it belongs to the user's account
Also history module should set a flag indicated when transfer made as a loopback (to myself)

**Comment by EvgenKor** [comment]
Implemented in PR #53 
<img width="1012" alt="image" src="https://user-images.githubusercontent.com/1415489/200026366-ff013848-6546-4df3-8ab4-0527f2c7cb0a.png">

**Comment by maikReal** [comment]
@vadimnikonov1 Better to test this task using local machine

**Comment by vadimnikonov1** [comment]
QA review - OK
