### ISSUE TITLE
[Support V2] Add changes to logs for new support version

### ISSUE THREAD

**Issue by maikReal** [zkBob/zkbob-client-js#56]
### Wha to do?

1. Add a new field ( Trace ID = Support ID) to the sendTransactions relayer service
2. Add Trace Id to every log message along with Job Id ( if it was already created)

The part of the big task for Support V2 – https://www.notion.so/blockscout/Establish-support-process-d93aeb68739d46808e17eee27263044c

Relates to:
- https://github.com/zkBob/zeropool-relayer/issues/100
- https://github.com/zkBob/zkbob-ui/issues/94

**Comment by EvgenKor** [comment]
The task is completed and currently deployed on staging
