### ISSUE TITLE
Client self-healing

### ISSUE THREAD

**Issue by r0wdy1** [zkBob/zkbob-client-js#63]
Problem: client application's roots can diverge from relayer's, so that further sync leads to different values.
Example of error: 
```
Nov 28 07:45:30 [relayer-mpv](https://my.papertrailapp.com/systems/relayer-mpv/events?focus=1533911951141924901&selected=1533911951141924901) [zk-zkbob-relayer-1/bac491289b8b](https://my.papertrailapp.com/events?q=program%3Azk-zkbob-relayer-1%2Fbac491289b8b&focus=1533911951141924901&selected=1533911951141924901)  #033[33mwarn#033[39m: Validation error: Incorrect root at index 938496: given 16487994424135461758197250592886238238853390102054304303685024917621785913544, expected 12288694896256461778204082089754840045221114890208831775726614887524104710954 {"timestamp":"2022-11-28T15:45:30.257Z"}
```

Client library should perform check current root against contract by current client's index ( it can be in the past, it doesn't matter).
If the roots are not equal,  the self-healing sequence must be started:
1. Apply binary search for equal roots ( make a big step back, compare,  then make  half a step further, compare  etc )
2. Rollback client state to the index where roots were equal
3. Sync up to the current index

**Comment by EvgenKor** [comment]
PR #66
