### ISSUE TITLE
Shielded  address for different pools

### ISSUE THREAD

**Issue by maikReal** [zkBob/zkbob-client-js#68]
## Why we need to do this task?
Right now we have one zkAddress that valid only for specific net and pool (currently for Polygon)

For creating pools on other nets we can face with the problem that a user from Binance net couldn’t transfer Bob tokens to a user to Polygon net for example

## What to do?

1. We need to support generating zkAddress with a prefix for a specific network. E.g. **POL_GbyFdqLe....** for Polygon OR **BNB_GbyFdqLe....** for Binance
2. Support creating global addresses that will not relate to a specific pool and network. So, users from any network can send BOB to this address. It'll be an advanced setting for a user during generating his address in zkBob

Then in UI, we will create a flow, so our users could:
1. Create a global address using advanced settings
2. Create a local address that will relate to a specific pool and network 

[More detailed here](https://www.notion.so/blockscout/Shielded-address-for-different-pools-510e561e7c624975afc2f4bbfd219c2a)

**Comment by EvgenKor** [comment]
#117
