### ISSUE TITLE
Params lazy loading

### ISSUE THREAD

**Issue by r0wdy1** [zkBob/zkbob-client-js#81]
Params need to be downloaded only if
1.  delegated prover is not used
2. delegated prover is used, but request has failed and fallback option is set 

In both cases params must be downloaded as a background process.
Download process status must be checked when the user tries to perform a transaction.

**Comment by AllFi** [comment]
- [ ] https://github.com/zkBob/zkbob-client-js/pull/80
- [ ] https://github.com/zkBob/zkbob-console/pull/43
- [ ] UI

**Comment by maikReal** [comment]
Blocked by:
- https://github.com/zkBob/zkbob-prover/issues/1

Can't be deployed on staging without delegated prover

**Comment by maikReal** [comment]
@vadimnikonov1 Test in prod

**Comment by AllFi** [comment]
We need to check the following:
* If the delegated prover is not used then params loading should be started in the background right after account creation
* If the params loading process is not finished when the user is trying to make tx then we should wait until the params are loaded and start to prove tx right after that.
* If the params loading process failed we should try to load params again when the user tries to perform a new tx.
* If the delegated prover is used (Delegated mode) we shouldn't load the params even if the delegated prover doesn't work or works incorrectly.
* `zkbob-client-js` has another proving mode: DelegatedWithFallback. In this mode, we load params and try to prove tx locally if the delegated prover doesn't work or works incorrectly. But the ui doesn't support it so it can be tested only with the console.

The Local mode can be tested with vanilla ui. The Delegated mode can be tested with gift cards ui.

**Comment by vadimnikonov1** [comment]
QA review - OK
