### ISSUE TITLE
Fetch direct deposits from contracts

### ISSUE THREAD

**Issue by r0wdy1** [zkBob/zkbob-client-js#93]
1. Get list of of completed direct deposit from relayer ( included in /transactions )
2. Get list of pending and refunded deposits ( TBD dedicated subgraph)
3. Merge the lists and  deduplicate rows. If a record is presented in both list, use the one from relayer
4. Filter by owned zk address ( same as with regular transfers)
5. include dd list in history view for UI

**Comment by maikReal** [comment]
Relates to:
- https://github.com/zkBob/zkbob-contracts/issues/28

**Comment by maikReal** [comment]
Probably can't implement till Denver

**Comment by maikReal** [comment]
@r0wdy1 @EvgenKor Increased the priority because we need to finish this task for the ETH pool on OP

**Comment by maikReal** [comment]
@r0wdy1 @EvgenKor Could you please provide estimations for this task?
