### ISSUE TITLE
History records absence in some cases

### ISSUE THREAD

**Issue by EvgenKor** [zkBob/zkbob-client-js#95]
Sometimes RPC node does not return transaction calldata to build а history record. In such case the history record can be omitted. It's need to workaround to retrying transaction fetching

<img width="1104" alt="image" src="https://user-images.githubusercontent.com/1415489/216291020-f448389b-5f40-495f-acfb-47aff7f74aef.png">

**Comment by maikReal** [comment]
@EvgenKor Deploy on staging this week (14.02)

**Comment by EvgenKor** [comment]
In production currently
